language: java
jdk: oraclejdk11
before_script:
  ./install-java-dependencies.sh
script:
  - cd ./java && mvn clean package

language: r
  - 3.6.3
r_packages:
  - testthat
  - RJSONIO
before_script:
  - cd r-package
script:
  - mkdir ./inst/
    mkdir ./inst/java
    cp ../java/rcoboldi-assembly/target/rcoboldi-assembly-*-RELEASE.jar ./inst/java
    R -e 'roxygen2::roxygenize("./", roclets = c("rd", "collate", "namespace", "vignette"))'
    cd .. && R CMD INSTALL --preclean --no-multiarch --with-keep.source r-package

dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change
