stages:
  - buildJavaDependencies
  - buildRPackage

jobs:
  include:
    - stage: "buildJavaDependencies"
      name: "Build Java Dependencies"
      language: java
      jdk: oraclejdk11
      env:		
        global:		
          #
          # This is here to fix a 'peer not authenticated' error which causes the build to fail
          # when attempting to download dependencies from FuseSource.
          #
          - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
      before_script:
        ./install-java-dependencies.sh
      script:
        - cd ./java && mvn clean package
    - stage: "buildRPackage"
      name: "Build R Package"
      language: r
      r:
        - release
      cache: packages
      install:
        - Rscript -e 'install.packages(c("devtools","roxygen2","testthat", "RJSONIO"));devtools::install_deps("r-package")'
      before_script:
        - cd r-package
          mkdir ./inst/
          mkdir ./inst/java
          cp ../java/rcoboldi-assembly/target/rcoboldi-assembly-*-RELEASE.jar ./inst/java
      script:
        - Rscript -e 'devtools::check(".")'

dist: bionic

notifications:
  email:
    on_success: change
    on_failure: change
