matrix:
  include:
    - language: java
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
      before_script:
        ./install-java-dependencies.sh
      script:
        - cd ./java && mvn clean package

matrix:
  include:
    - language: r
      r: 3.6.3
      before_script:
        - cd r-package
      script:
        - mkdir ./r-package/inst/
          mkdir ./r-package/inst/java
          cp ./java/rcoboldi-assembly/target/rcoboldi-assembly-*-RELEASE.jar ./r-package/inst/java
          R -e 'install.packages("RJSONIO")'
          R -e 'roxygen2::roxygenize("/home/rstudio/rcoboldi/r-package/", roclets = c("rd", "collate", "namespace", "vignette"))'
          cd /home/rstudio/rcoboldi/ && R CMD INSTALL --preclean --no-multiarch --with-keep.source r-package

dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change
