language: java
env: JDK='Oracle JDK 11'
install: ~/bin/install-jdk.sh --target "/home/travis/oraclejdk11" --feature "11" --license "BCL"
before_script:
  ./install-java-dependencies.sh
script:
  - cd ./java && mvn clean package

language: r
before_script:
  - cd r-package
script:
  - mkdir ./inst/
    mkdir ./inst/java
    cp ../java/rcoboldi-assembly/target/rcoboldi-assembly-*-RELEASE.jar ./inst/java
    R -e 'install.packages("RJSONIO")'
    R -e 'roxygen2::roxygenize("./", roclets = c("rd", "collate", "namespace", "vignette"))'
    cd .. && R CMD INSTALL --preclean --no-multiarch --with-keep.source r-package

dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change
