stages:
  - buildJavaDependencies
  - buildRPackage

jobs:
  include:
    - stage: "buildJavaDependencies"
      name: "Build Java Dependencies"
      language: java
      jdk: oraclejdk11
      before_script:
        ./travis-install-java-dependencies.sh
      script:
        - cd ./java && mvn clean package && cd /home/travis/build/thospfuller/rcoboldi
    - stage: "buildRPackage"
      name: "Build R Package"
      language: r
      r:
        - release
      cache: packages
      install:
        - Rscript -e 'install.packages(c("devtools","roxygen2","testthat", "RJSONIO"));devtools::install_deps("r-package")'
      before_script:
        - mkdir ./r-package/inst/ && mkdir ./r-package/inst/java && cd /home/travis/build/thospfuller/rcoboldi && ./cp-jar-to-inst-java.sh
      script:
        - Rscript -e 'devtools::check(".")'

dist: bionic

notifications:
  email:
    on_success: change
    on_failure: change
